Blog post announcing 1.9.2
YOURLS/website pull request #101
Opened 2023-02-26 18:18 UTC by ozh

@LeoColomb and @dgw , fancy a proof reading ?

(don't commit the PR, I want to sync it with the release itself)

2023-02-26 19:34 UTC, LeoColomb requested changes
Overall looks good! 👌
One comment, one tiny rephrasing and this impossible space before punctuation 😁

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +We're pleased to announce the release of [YOURLS 1.9.2](https://github.com/YOURLS/YOURLS/releases/tag/1.9.2) !
```suggestion
We're pleased to announce the release of [YOURLS 1.9.2](https://github.com/YOURLS/YOURLS/releases/tag/1.9.2)!
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +Some new features, improvements, and bug fixes that make YOURLS even better than before, obviously :)
```suggestion
Some new features, improvements, and bug fixes that make YOURLS even better than before, obviously 🙂
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +For this release, I would like to thank all the contributors who helped make YOURLS better : @barryhughes, @nexxai, @SXN31, @jarebear6expepjozn6rakjq5iczi3irqwphcvb, @4BRobby, along with the usual cr
```suggestion
For this release, I would like to thank all the contributors who helped make YOURLS better: @barryhughes, @nexxai, @SXN31, @jarebear6expepjozn6rakjq5iczi3irqwphcvb, @4BRobby, along with the usual crew @ozh, @LeoColomb and @dgw.
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +# More goodness : the website
```suggestion
# More goodness: the website
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +The [YOURLS website](https://yourls.org/) has been completely redesigned : under the same domain you'll find the [documentation](https://yourls.org/docs/), the [blog](https://yourls.org/blog/), all p
```suggestion
The [YOURLS website](https://yourls.org/) has been completely redesigned: under the same domain you'll find the [documentation](https://yourls.org/docs), the [blog](https://yourls.org/blog), all powered by a static site generator using simple markdown files hosted on Github ([YOURLS/website](https://github.com/YOURLS/website)).
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +Benefits : faster page loads, extensive search feature, and everyone can contribute with a simple pull request !
👍 

```suggestion
Benefits: faster page loads, extensive search feature, and everyone can contribute with a simple pull request!
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +## How to update to YOURLS 1.9.2 ?
```suggestion
## How to update to YOURLS 1.9.2?
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +And as always, if it's been a long time since your last DB backup, now would be a good time to do it ;)
```suggestion
And as always, if it's been a long time since your last DB backup, now would be a good time to do it 😉
```

2023-02-26 19:34 UTC, LeoColomb commented on blog/2023-02-27-yourls-1-9-2.md
> +slug: /2023/02/yourls-1-9-2
```suggestion
```

The previous slug attributes were there for compatibility with the previous blog system.
Unless the more generic `/YYYY/MM/DD/title` is a no-go for you, we can safely drop it 🙂

2023-02-26 21:04 UTC, dgw reviewed
Just one thing from me to add to @LeoColomb's thorough proofing job 😁

2023-02-26 21:04 UTC, dgw commented on blog/2023-02-27-yourls-1-9-2.md
> +The [YOURLS website](https://yourls.org/) has been completely redesigned: under the same domain you'll find the [documentation](https://yourls.org/docs), the [blog](https://yourls.org/blog), all powe
```suggestion
The [YOURLS website](https://yourls.org/) has been completely redesigned. Under the same domain you'll find introductory pages as before, the [documentation](https://yourls.org/docs), and the [blog](https://yourls.org/blog)—all powered by a static site generator using simple markdown files hosted on Github ([YOURLS/website](https://github.com/YOURLS/website)).
```

2023-02-28 10:50 UTC, LeoColomb approved these changes

2023-03-05 11:27 UTC, merged